from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("brds"):
        for statement in [
            "CREATE TABLE IF NOT EXISTS brd_versions (version_id INTEGER PRIMARY KEY AUTOINCREMENT, brd_id TEXT NOT NULL, version INTEGER NOT NULL, parent_version_id INTEGER, quality_status TEXT NOT NULL DEFAULT 'READY', status_reason TEXT, created_at TEXT NOT NULL, UNIQUE(brd_id, version))",
            "CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT NOT NULL, actor_type TEXT NOT NULL, actor_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, result TEXT NOT NULL, details_json TEXT NOT NULL, request_id TEXT)",
            "CREATE TABLE IF NOT EXISTS hitl_sessions (session_id TEXT PRIMARY KEY, analysis_id TEXT NOT NULL, brd_id TEXT NOT NULL, status TEXT NOT NULL, current_question_id TEXT, follow_up_round INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS hitl_answers (answer_id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, question_id TEXT NOT NULL, answer TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(session_id, question_id))",
            "CREATE TABLE IF NOT EXISTS resolved_requirements_models (resolved_id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, model_version_id INTEGER NOT NULL, source_model_version_id INTEGER NOT NULL, created_at TEXT NOT NULL)",
        ]:
            bind.execute(sa.text(statement))
        return
    op.create_table("brds", sa.Column("brd_id", sa.String(), primary_key=True), sa.Column("title", sa.String()), sa.Column("source_filename", sa.String(), nullable=False), sa.Column("file_type", sa.String(), nullable=False), sa.Column("original_content", sa.Text()), sa.Column("created_at", sa.String(), nullable=False), sa.Column("updated_at", sa.String(), nullable=False))
    op.create_table("requirements_models", sa.Column("model_version_id", sa.Integer(), primary_key=True), sa.Column("brd_id", sa.String(), sa.ForeignKey("brds.brd_id"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("model_json", sa.Text(), nullable=False), sa.Column("created_at", sa.String(), nullable=False), sa.UniqueConstraint("brd_id", "version"))
    op.create_table("requirements", sa.Column("model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id", ondelete="CASCADE"), nullable=False), sa.Column("requirement_id", sa.String(), nullable=False), sa.Column("type", sa.String(), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("source_json", sa.Text(), nullable=False), sa.Column("priority", sa.String()), sa.PrimaryKeyConstraint("model_version_id", "requirement_id"))
    op.create_table("analyses", sa.Column("analysis_id", sa.String(), primary_key=True), sa.Column("brd_id", sa.String(), sa.ForeignKey("brds.brd_id"), nullable=False), sa.Column("model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id"), nullable=False), sa.Column("status", sa.String(), nullable=False), sa.Column("summary_json", sa.Text(), nullable=False), sa.Column("created_at", sa.String(), nullable=False))
    op.create_table("issues", sa.Column("issue_id", sa.String(), nullable=False), sa.Column("analysis_id", sa.String(), sa.ForeignKey("analyses.analysis_id", ondelete="CASCADE"), nullable=False), sa.Column("model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id"), nullable=False), sa.Column("type", sa.String(), nullable=False), sa.Column("severity", sa.String(), nullable=False), sa.Column("title", sa.String(), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("severity_reason", sa.Text(), nullable=False), sa.Column("clarification_required", sa.Boolean(), nullable=False), sa.Column("created_at", sa.String(), nullable=False), sa.PrimaryKeyConstraint("analysis_id", "issue_id"))
    op.create_table("issue_requirements", sa.Column("analysis_id", sa.String(), nullable=False), sa.Column("issue_id", sa.String(), nullable=False), sa.Column("model_version_id", sa.Integer(), nullable=False), sa.Column("requirement_id", sa.String(), nullable=False), sa.ForeignKeyConstraint(["analysis_id", "issue_id"], ["issues.analysis_id", "issues.issue_id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["model_version_id", "requirement_id"], ["requirements.model_version_id", "requirements.requirement_id"]), sa.PrimaryKeyConstraint("analysis_id", "issue_id", "requirement_id"))
    op.create_table("clarification_questions", sa.Column("question_id", sa.String(), nullable=False), sa.Column("analysis_id", sa.String(), sa.ForeignKey("analyses.analysis_id", ondelete="CASCADE"), nullable=False), sa.Column("issue_id", sa.String(), nullable=False), sa.Column("model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id"), nullable=False), sa.Column("question", sa.Text(), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("priority", sa.String(), nullable=False), sa.Column("status", sa.String(), nullable=False), sa.Column("created_at", sa.String(), nullable=False), sa.ForeignKeyConstraint(["analysis_id", "issue_id"], ["issues.analysis_id", "issues.issue_id"]), sa.PrimaryKeyConstraint("analysis_id", "question_id"))
    op.create_table("question_requirements", sa.Column("analysis_id", sa.String(), nullable=False), sa.Column("question_id", sa.String(), nullable=False), sa.Column("model_version_id", sa.Integer(), nullable=False), sa.Column("requirement_id", sa.String(), nullable=False), sa.ForeignKeyConstraint(["analysis_id", "question_id"], ["clarification_questions.analysis_id", "clarification_questions.question_id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["model_version_id", "requirement_id"], ["requirements.model_version_id", "requirements.requirement_id"]), sa.PrimaryKeyConstraint("analysis_id", "question_id", "requirement_id"))
    op.create_table("brd_versions", sa.Column("version_id", sa.Integer(), primary_key=True), sa.Column("brd_id", sa.String(), sa.ForeignKey("brds.brd_id"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("parent_version_id", sa.Integer(), sa.ForeignKey("brd_versions.version_id")), sa.Column("quality_status", sa.String(), nullable=False), sa.Column("status_reason", sa.Text()), sa.Column("created_at", sa.String(), nullable=False), sa.UniqueConstraint("brd_id", "version"))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("timestamp", sa.String(), nullable=False), sa.Column("actor_type", sa.String(), nullable=False), sa.Column("actor_id", sa.String()), sa.Column("action", sa.String(), nullable=False), sa.Column("entity_type", sa.String(), nullable=False), sa.Column("entity_id", sa.String(), nullable=False), sa.Column("result", sa.String(), nullable=False), sa.Column("details_json", sa.Text(), nullable=False), sa.Column("request_id", sa.String()))
    op.create_table("hitl_sessions", sa.Column("session_id", sa.String(), primary_key=True), sa.Column("analysis_id", sa.String(), sa.ForeignKey("analyses.analysis_id"), nullable=False), sa.Column("brd_id", sa.String(), sa.ForeignKey("brds.brd_id"), nullable=False), sa.Column("status", sa.String(), nullable=False), sa.Column("current_question_id", sa.String()), sa.Column("follow_up_round", sa.Integer(), nullable=False), sa.Column("created_at", sa.String(), nullable=False), sa.Column("updated_at", sa.String(), nullable=False))
    op.create_table("hitl_answers", sa.Column("answer_id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.String(), sa.ForeignKey("hitl_sessions.session_id", ondelete="CASCADE"), nullable=False), sa.Column("question_id", sa.String(), nullable=False), sa.Column("answer", sa.Text(), nullable=False), sa.Column("created_at", sa.String(), nullable=False), sa.UniqueConstraint("session_id", "question_id"))
    op.create_table("resolved_requirements_models", sa.Column("resolved_id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.String(), sa.ForeignKey("hitl_sessions.session_id"), nullable=False), sa.Column("model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id"), nullable=False), sa.Column("source_model_version_id", sa.Integer(), sa.ForeignKey("requirements_models.model_version_id"), nullable=False), sa.Column("created_at", sa.String(), nullable=False))

def downgrade():
    for table in ["resolved_requirements_models", "hitl_answers", "hitl_sessions", "audit_logs", "brd_versions", "question_requirements", "clarification_questions", "issue_requirements", "issues", "analyses", "requirements", "requirements_models", "brds"]:
        op.drop_table(table)
